### ISSUE TITLE
adding pathways| Error: No model reactions found and Error: Error in !opt$sbml.no.output : invalid argument type

### ISSUE THREAD

**Issue by wtscott31** [jotech/gapseq#211]
Hi, 

I wonder how I can troubleshoot the following errors when adding certain pathways to my genome-scale models of interest. I am trying to add chlorobenzene degradation pathways to a model that I see are contained in the gapseq database files meta_rea_pwy-gapseq.tbl and meta_pwy.tbl. However, when running certain commands to add the following pathways I obtain the respective errors : 1,2,4-trichlorobenzene degradation

./gapseq adapt -m "/UNLOCK/Dehalobacter_restrictus.RDS" -a "PWY-6091"

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
         id     id.type   db.rxn seed
1: PWY-6091 metacyc pwy RXN-9877     
2: PWY-6091 metacyc pwy RXN-9880     
Error: No model reactions found
Execution halted

1,4-dichlorobenzene degradation

./gapseq adapt -a 14DICHLORBENZDEG-PWY -m /UNLOCK/Dehalobacter_restrictus.RDS

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
                     id     id.type                      db.rxn
1: 14DICHLORBENZDEG-PWY metacyc pwy              DIOXYXANFL-RXN
2: 14DICHLORBENZDEG-PWY metacyc pwy            CHLOROBENDDH-RXN
3: 14DICHLORBENZDEG-PWY metacyc pwy          CHLOROCATDIOXY-RXN
4: 14DICHLORBENZDEG-PWY metacyc pwy           DIENELACHYDRO-RXN
5: 14DICHLORBENZDEG-PWY metacyc pwy           CHLOROMALERED-RXN
6: 14DICHLORBENZDEG-PWY metacyc pwy MALEYLACETATE-REDUCTASE-RXN
7: 14DICHLORBENZDEG-PWY metacyc pwy                   RXN-18360
8: 14DICHLORBENZDEG-PWY metacyc pwy                   RXN-18361
9: 14DICHLORBENZDEG-PWY metacyc pwy                   RXN-18362
                                                                                                          seed
1:                                                                                                            
2:                                                                                                            
3:                                                                                                            
4: rxn02747 rxn03800 rxn03801 rxn04650 rxn04653 rxn07908 rxn07909 rxn15998 rxn16082 rxn16084 rxn31706 rxn31716
5:                                                                rxn02141 rxn02142 rxn03656 rxn16086 rxn20159
6:                                                                rxn02141 rxn02142 rxn03656 rxn16086 rxn20159
7:                                                                                           rxn03018 rxn03694
8:                                                                                                            
9:                                                                                                            
[1] "Reactions already in model:  "
[1] "Reactions not in gapseq reaction database:  rxn03656,rxn20159,rxn31706,rxn31716"
[1] "Added reactions:  rxn02141,rxn02142,rxn02747,rxn03018,rxn03694,rxn03800,rxn03801,rxn04650,rxn04653,rxn07908,rxn07909,rxn15998,rxn16082,rxn16084,rxn16086"
Error in !opt$sbml.no.output : invalid argument type
Execution halted

1,2-dichlorobenzene degradation

./gapseq adapt -a PWY-6090 -m /UNLOCK/Dehalobacter_restrictus.RDS

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
         id     id.type   db.rxn seed
1: PWY-6090 metacyc pwy RXN-9878     
2: PWY-6090 metacyc pwy RXN-9879     
Error: No model reactions found
Execution halted

1,3-dichlorobenzene degradation

./gapseq adapt -a PWY-6081 -m /UNLOCK/Dehalobacter_restrictus.RDS

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
         id     id.type   db.rxn seed
1: PWY-6081 metacyc pwy RXN-9853     
2: PWY-6081 metacyc pwy RXN-9854     
Error: No model reactions found
Execution halted

chlorobenzene degradation

./gapseq adapt -a PWY-6083 -m /UNLOCK/Dehalobacter_restrictus.RDS

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
         id     id.type   db.rxn seed
1: PWY-6083 metacyc pwy RXN-9858     
2: PWY-6083 metacyc pwy RXN-9859     
Error: No model reactions found
Execution halted

Please let me know how I can rectify these issues. Thanks in advance!

The output that I obtain from "./gapseq test" is: /gapseq test

gapseq version: 1.2 13661828
linux-gnu
#1 SMP Tue Sep 13 07:51:46 UTC 2022 

#######################
#Checking dependencies#
#######################
ldconfig (Ubuntu GLIBC 2.31-0ubuntu9.12) 2.31
libsbml.so.5 -> libsbml.so.5.18.0
libglpk.so.40 -> libglpk.so.40.3.1
GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)
sed (GNU sed) 4.8
grep (GNU grep) 3.11
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.14.1+
exonerate from exonerate version 2.4.0
bedtools v2.31.1
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.3.2 (2023-10-31) -- "Eye Holes"
git version 2.42.0
GNU parallel 20231122
HMMER 3.4 (Aug 2023); http://hmmer.org/
bc 1.07.1

Missing dependencies: 0

#####################
#Checking R packages#
#####################
data.table 1.14.8 
stringr 1.5.1 
sybil 2.2.0 
getopt 1.20.4 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.12.3 
stringi 1.8.2 
glpkAPI 1.3.4 
BiocManager 1.30.22 
Biostrings 2.68.1 
jsonlite 1.8.7 
CHNOSZ 2.0.0 
httr 1.4.7 

Missing R packages:  0 

##############################
#Checking basic functionality#
##############################
Optimization test: OK 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

**Comment by jotech** [comment]
hi @wtscott31 

From your output, I would say that adding the pathway 14DICHLORBENZDEG-PWY should have worked, whereas for the pathways PWY-6083, PWY-6081, PWY-6090, PWY-6091 no candidate reaction could be found in the gapseq reactions. I suppose that the mapping from metacyc to gapseq reactions is missing here.
I will try to have a look later this week!

The error you got for 14DICHLORBENZDEG-PWY (` Error in !opt$sbml.no.output : invalid argument type`) was already fixed by this commit 6fefcb5e4bfd2594f6f116a01b6072dbe3ceefb8 and should be solved after updating to the latest gapseq version. Could you give it a try?

**Comment by wtscott31** [comment]
Hi there @jotech,

Thanks for your quick response and guidance. I followed your advice and updated to the latest version of gapseq, and I'm happy to report that it did resolve the issue with adding the pathway 14DICHLORBENZDEG-PWY. Your support on this was spot on, and I appreciate it.

However, I'm still encountering an issue with the other pathways (PWY-6083, PWY-6081, PWY-6090, PWY-6091). Despite the successful update, I get the "Error: No model reactions found" message when trying to add these pathways. It seems like the candidate reactions for these pathways might not be mapped in gapseq as you mentioned.

I understand you're planning to look into this later in the week, and I just wanted to confirm these ongoing issues on my end. Any further insights or updates you could provide would be greatly appreciated.

Thanks again for your help and looking forward to any suggestions you might have.

Best regards,

@wtscott31

**Comment by wtscott31** [comment]
@jotech I tried running the latest version of gapseq with the added dehalogenation reactions from 3 days ago. However, I still obtain the no model reactions found error. This is odd given that the "meta_rea_pwy-gapseq.tbl" contains all the specified reactions and pathways. Do you think I should just manually add them to the models? Also, if there is a new version of gapseq, can you list or specify the new version in the release? Thanks!

**Comment by jotech** [comment]
hi @wtscott31 
I'm sorry it took me some time, but there should be suitable candidate reactions for all the pathways by now!

What needs to be checked is if chlorobenzene degradation also works in final fba models. (for dehalogenation of PCE/TCE it's already working)
In addition, detecting the pathways by `gapseq find` might be difficult because of missing sequences. Do you have a candidate genome I could use for testing? I used Pseudomonas nitroreducens, and the pathways couldn't be detected.

**Comment by wtscott31** [comment]
Hi @jotech,

Thank you for your message and for your assistance so far. I am still experiencing difficulties adding the reactions and pathways, and I don't believe I have a candidate genome at this time. When I attempt to run the command, I receive the following error:

`./gapseq adapt -a rxn04664,rxn04665,rxn07170 -m /UNLOCK/Dehalobacter_restrictus.RDS -c /UNLOCK/Dehalobacter_restrictus-rxnWeights.RDS -g /UNLOCK/Dehalobacter_restrictus-rxnXgenes.RDS -b /UNLOCK/Dehalobacter_restrictus-all-Reactions.tbl

Loading model files /UNLOCK/Dehalobacter_restrictus.RDS 
         id  id.type db.rxn     seed
     <char>   <char> <char>   <char>
1: rxn04664 seed rxn        rxn04664
2: rxn04665 seed rxn        rxn04665
3: rxn07170 seed rxn        rxn07170
[1] "Reactions already in model:  "
[1] "Reactions not in gapseq reaction database:  rxn04664,rxn04665,rxn07170"
Error: No reactions can be added.
Execution halted
`
Your help is greatly appreciated.
