### ISSUE TITLE
Query subunit fasta issue

### ISSUE THREAD

**Issue by Waschina** [jotech/gapseq#7]
I encountered an issue when predicting pathways with polymer protein complexes.

Example command that reproduces the error:

`../../gapseq/./gapseq.sh -b 200 -p dichloroethane GCF_000005845.2_ASM584v2_genomic.fna.gz `

Please note that you can add any fasta file to reproduce the error. The output of the command is stated below.

```
Number of pathways to be considered: 1

1/1: Checking for pathway |12DICHLORETHDEG-PWY| 1,2-dichloroethane degradation
(Degradation,CHLORINATED-COMPOUNDS-DEG)
	DHLAXANAU-RXN 1,2-dichloroethane dehalogenase 3.8.1.5
		/home/swaschina/workspace-kiel/2018/gapseq/dat/seq/Bacteria/unipac90/3.8.1.5.fasta
		NO blast hit
	MOXXANAU-RXN 2-chloroethanol dehydrogenase 1.1.2.7
		/home/swaschina/workspace-kiel/2018/gapseq/dat/seq/Bacteria/unipac90/1.1.2.7.fasta
ls: cannot access 'query_subunit.part-*.fasta': No such file or directory
rm: cannot remove 'query_subunit.part-*.fasta*': No such file or directory
		total subunits found: 0 / 3
		NO hit because of missing subunits
	ALDXANAU-RXN chloroacetaldehyde dehydrogenase 1.2.1.4
		/home/swaschina/workspace-kiel/2018/gapseq/dat/seq/Bacteria/unipac90/1.2.1.4.fasta
		Blast hit (5x)
			bit=350 id=43.142 cov=99 hit=UniRef90_Q8GAK7
			bit=252 id=34.879 cov=99 hit=UniRef90_Q8GAK7
			bit=224 id=32.969 cov=99 hit=UniRef90_Q8GAK7
		Candidate reaction for import: 6
	DHLBXANAU-RXN chloroacetate dehalogenase 3.8.1.3
		/home/swaschina/workspace-kiel/2018/gapseq/dat/seq/Bacteria/unipac90/3.8.1.3.fasta
		NO good blast hit
			(best one: bit=54.3 id=25.225 cov=91)
Pathway completeness: 1/4 (25%)
Hits with candidate reactions in database: 1/4
Key reactions: 0/1

Pathways found:

Candidate reactions found: 6 

%CPU %MEM CMD
 0.7  0.0 /bin/bash ../../gapseq/./gapseq.sh -b 200 -p dichloroethane GCF_000005845.2_ASM584v2_genomic.fna.gz
Running time: 6 s.

```

The error messages are:
```
ls: cannot access 'query_subunit.part-*.fasta': No such file or directory
rm: cannot remove 'query_subunit.part-*.fasta*': No such file or directory
```

**Comment by jotech** [comment]
should be fixed. please reopen in case of further problems!

**Comment by jinnjy** [comment]
Hi,

This is again happened in the version I cloned from github on Mar 13, 2021.

(antismash5) [jinnjy@origo gapseq]$ ./gapseq doall /home/jinnjy/DATA/genomes/Prokaryotes/batch3/GCA_004936435.1_ASM493643v1_genomic.fna
index file GCA_004936435.1_ASM493643v1_genomic.fna.tmp.fai not found, generating...
Predicted taxonomy: Bacteria
Checking updates for Bacteria /home/jinnjy/Tools/gapseq/gapseq/src/../dat/seq/Bacteria
2021-05-18 10:06:05 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
2021-05-18 10:06:09 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
2021-05-18 10:06:12 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
Bacteria reviewed sequences already up-to-date
Bacteria unreviewed sequences already up-to-date
Bacteria additional reaction sequences already up-to-date
        Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [tblastn] lcl|Query_1 UniRef50_O30642 Monomethylamine methyltransferase MtmB1 n=104 Tax=cellular organisms TaxID=131567 RepID=MTMB1_METBA: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 201
Warning: [tblastn] lcl|Query_1 UniRef90_Q18TV3 Trimethylamine methyltransferase MttB n=7 RepID=MTTB_DESHD: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 330
ls: cannot access 'query_subunit.part-*.fasta': No such file or directory
rm: cannot remove 'query_subunit.part-*.fasta*': No such file or directory

**Comment by jinnjy** [comment]
More specifically, this only happened if I use "doall".
Everything was fine when I later separated the execution of different steps by following the top figure of https://gapseq.readthedocs.io/en/latest/usage/basics.html:
./gapseq find -p all 
./gapseq find-transport
./gapseq draft 
./gapseq fill 

The account I used on the server of my institution has no administrator access.

> 
> 
> Hi,
> 
> This is again happened in the version I cloned from github on Mar 13, 2021.
> 
> (antismash5) [jinnjy@origo gapseq]$ ./gapseq doall /home/jinnjy/DATA/genomes/Prokaryotes/batch3/GCA_004936435.1_ASM493643v1_genomic.fna
> index file GCA_004936435.1_ASM493643v1_genomic.fna.tmp.fai not found, generating...
> Predicted taxonomy: Bacteria
> Checking updates for Bacteria /home/jinnjy/Tools/gapseq/gapseq/src/../dat/seq/Bacteria
> 2021-05-18 10:06:05 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
> 2021-05-18 10:06:09 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
> 2021-05-18 10:06:12 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
> Bacteria reviewed sequences already up-to-date
> Bacteria unreviewed sequences already up-to-date
> Bacteria additional reaction sequences already up-to-date
> Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
> Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
> Warning: [tblastn] lcl|Query_1 UniRef50_O30642 Monomethylamine methyltransferase MtmB1 n=104 Tax=cellular organisms TaxID=131567 RepID=MTMB1_METBA: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 201
> Warning: [tblastn] lcl|Query_1 UniRef90_Q18TV3 Trimethylamine methyltransferase MttB n=7 RepID=MTTB_DESHD: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 330
> ls: cannot access 'query_subunit.part-_.fasta': No such file or directory rm: cannot remove 'query_subunit.part-_.fasta*': No such file or directory

**Comment by Waschina** [comment]
Thank for sharing the details and logs. We will look into it this week.
Best
Silvio

**Comment by jinnjy** [comment]
Sorry I was still wrong, there are still cases for executing **gapseq find**:
This is the command I used.
**./gapseq find -p all -v 0 /home/jinnjy/DATA/genomes/Prokaryotes/Acidobacteria_20210518_fna/fna/GCA_000014005.1_ASM1400v1_genomic.fna**

And the following are the messages:

2021-05-25 16:47:46 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
2021-05-25 16:47:49 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
2021-05-25 16:47:52 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
Bacteria reviewed sequences already up-to-date
Bacteria unreviewed sequences already up-to-date
Bacteria additional reaction sequences already up-to-date
Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [tblastn] lcl|Query_6 UniRef50_A0A6J4S0Y1 Aspartyl-tRNA(Asn) amidotransferase subunit C @ Glutamyl-tRNA(Gln) amidotransferase subunit C (Fragment) n=1 Tax=uncultured Solirubrobacteraceae bacterium TaxID=1162706 RepID=A0A6J4S0Y1_9ACTN Subunit 3: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [tblastn] lcl|Query_1 UniRef50_O30642 Monomethylamine methyltransferase MtmB1 n=104 Tax=cellular organisms TaxID=131567 RepID=MTMB1_METBA: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 201
Warning: [tblastn] lcl|Query_1 UniRef90_Q18TV3 Trimethylamine methyltransferase MttB n=7 RepID=MTTB_DESHD: Warning: One or more U or O characters replaced by X for alignment score calculations at positions 330
ls: cannot access 'query_subunit.part-*.fasta': No such file or directory
rm: cannot remove 'query_subunit.part-*.fasta*': No such file or directory

**Comment by Waschina** [comment]
Hi @jinnjy 

I figured out what causes the issue:
First, the [tblastn] are nothing to worry about here. Some (very few) reference protein sequences have non-standard letters in their amino acid sequences, which causes that a few alignments cannot be scored. Since this affects only a few (3-5) reference sequences this should not have a big effect on gapseq's output.
The second an bigger problem is the part 
```
ls: cannot access 'query_subunit.part-.fasta': No such file or directory
rm: cannot remove 'query_subunit.part-.fasta*': No such file or directory
```

This is caused by an erroneous fasta file in gapseq's reference sequence database. We'll make sure to correct this in the upcoming update of the reference sequences. Until now you can correct this error by running.

```sh
rm dat/seq/Bacteria/unrev/fff1a57554ea00ed065fb8ee193e2959.fasta
```

In addition, since the genome you have here is bacterial, you can also tell gapseq to limit the pathway search to pathways described for bacteria:

```
./gapseq find -p all -m Bacteria -v 0 /home/jinnjy/DATA/genomes/Prokaryotes/Acidobacteria_20210518_fna/fna/GCA_000014005.1_ASM1400v1_genomic.fna
```

Thanks for your feedback. I will post here again as soon as we fixed the reference sequences in gapseq.

**Comment by jinnjy** [comment]
Hi @Waschina,

Thanks for pointing out the reason these message pop up.
So far, gapseq is the best fit for the analysis I want to perform, it is a relieve that these warnings and errors look like relatively minor issues.

**Comment by jotech** [comment]
Hi @jinnjy 
we updated all sequences to avoid the issue @Waschina pointed out!
Hope it works better now :)

**Comment by jinnjy** [comment]
> 
> 
> Hi @jinnjy
> we updated all sequences to avoid the issue @Waschina pointed out!
> Hope it works better now :)

Thank you for the great helps. 
I updated the data before my new tests using the command.
git pull https://github.com/jotech/gapseq.git
I installed all the required package under an independent environment
conda create -n gapseq
conda activate gapseq
**I finished the following new tests only with warnings which you have explained why they might be happening.**
./gapseq find -p all -m Bacteria -v 0 /home/jinnjy/DATA/genomes/Prokaryotes/Acidobacteria_20210518_fna/fna/GCA_000014005.1_ASM1400v1_genomic.fna
./gapseq find-transport -v 0 /home/jinnjy/DATA/genomes/Prokaryotes/Acidobacteria_20210518_fna/fna/GCA_000014005.1_ASM1400v1_genomic.fna

**So we should be able to close this issue for now**

**Comment by Waschina** [comment]
Perfect, thanks for the feedback and please reopen if new issues occur.
